vim.scriptencoding = "utf-8"

local options = {
  helplang = 'ja,en',
  encoding = 'utf-8',
  fileencoding = 'utf-8',
  ambiwidth = 'double',
  termguicolors = true,
  swapfile = false,
  backup = false,
  writebackup = false,
  undofile = true,
  number = true,
  title = true,
  showcmd = true,
  showmode = false,
  showtabline = 2,
  hidden = true,
  signcolumn = 'number',
  splitright = true,
  splitbelow = true,
  cmdheight = 0,
  wrap = false,
  display = 'lastline',
  hlsearch = true,
  incsearch = true,
  ignorecase = true,
  smartcase = true,
  showmatch = false,
  scrolloff = 8,
  sidescrolloff = 8,
  virtualedit = 'block',
  expandtab = true,
  shiftwidth = 2,
  autoindent = true,
  smartindent = true,
  tabstop = 2,
  conceallevel = 0,
  completeopt = { 'menuone', 'noinsert', 'noselect' },
  pumheight = 10,
  clipboard = 'unnamedplus',
  mouse = 'a',
}

for k, v in pairs(options) do
	vim.opt[k] = v
end
