return {
  {
    'folke/noice.nvim',
    event = 'VeryLazy',
    dependencies = {
      'MunifTanjim/nui.nvim',
      'rcarriga/nvim-notify',
    },
    config = function()
      -- Correct as instructed in the error message generated by nvim-notify
      require('notify').setup {
        background_colour = '#000000'
      }

      -- Allow 2-byte character icons to be displayed when entering commands
      vim.fn.setcellwidths {
        { 0xf7d5, 0xf7d5, 1 },
        { 0xf002, 0xf002, 1 },
      }

      require('noice').setup {
        presets = {
          command_palette = true,
          long_message_to_split = true,
          inc_rename = false,
          lsp_doc_border = false,
        },
      }
    end,
  }
}
