return {
	{
		"folke/noice.nvim",
		event = "VeryLazy",
		dependencies = {
			"MunifTanjim/nui.nvim",
			"rcarriga/nvim-notify",
		},
		config = function()
			-- Correct as instructed in the error message generated by nvim-notify
			require("notify").setup({
				background_colour = "#000000",
			})

			require("noice").setup({
				messages = {
					view = "mini",
					view_error = "notify",
					view_warn = "notify",
					view_history = "messages",
					view_search = false,
				},
				presets = {
					command_palette = true,
					long_message_to_split = true,
				},
			})
		end,
	},
}
