add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

[directory]
truncation_length = 100

[cmd_duration]
min_time = 5000

